name: Node CI

on:
  - push
  - pull_request

env:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: make install
      - run: make lint
      - run: make test
      - uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: CC_TEST_REPORTER_ID
        with:
          coverageCommand: make test-coverage
          debug: true
